[main]
# Yazı Tipi Ayarı
font=Noto Sans Mono:size=9
layer=overlay
icons-enabled=yes
fields=name,categories
letter-spacing=1
inner-pad=5

# Konumlandırma Ayarları
anchor=top
y-margin=0
width=30

[colors]
# Yaru Dark Paleti
background=2c2c2cfe
text=#a8c8d9ff
match=d9534fff
selection=e95420ff
selection-text=ffffffff
selection-match=ffffffff
border=a8c8d9ff
